---
dependency:
  name: galaxy
role_name_check: 1
driver:
  name: podman
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: oraclelinux
    image: oraclelinux:9
    dockerfile: Dockerfile.j2
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: false
  # - name: ubuntu
  #   image: docker.io/pycontribs/ubuntu:latest
  #   pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - destroy

