---
- name: Download Vector packages
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
    dest: "./vector_{{ vector_version }}_amd64.deb"
    mode: "0755"
- name: Install Vector packages
  become: true
  ansible.builtin.apt:
    deb: vector_{{ vector_version }}_amd64.deb
- name: Vector | Apply template
  ansible.builtin.template:
    src: vector.yml.j2
    dest: "/etc/vector/vector.yml"
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
- name: Vector | change systemd unit
  ansible.builtin.template:
    src: vector.service.j2
    dest: /etc/systemd/system/vector.service
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    backup: true
  notify: Start Vector service
