dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: oraclelinux
    image: oraclelinux:9
    dockerfile: Dockerfile.j2
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: false
provisioner:
  name: ansible
verifier:
  name: ansible