---
dependency:
  name: galaxy
  enabled: true # to disable, set to false
driver:
  name: docker
lint: |
  ansible-lint .
  yamllint .
platforms:
  - name: ubuntu
    image: ubuntu:latest
    dockerfile: Dockerfile.j2
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: false
  - name: oraclelinux
    image: oraclelinux:9
    dockerfile: Dockerfile.j2
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: false
provisioner:
  name: ansible
  scenario:
    name: default